[package]
name = "dotrix"
version = "0.1.0"
authors = [
  "Elias Kartashov <elias@lowenware.com>",
  "Štěpán Wünsch <sw@lowenware.com>",
]
edition = "2018"
description = "3D Game Engine"
license = "MIT"

# [features]
# default = [
#     "my_feature",
# ]

[dependencies]
futures = { version = "0.3", default-features = false, features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.19"
strum_macros = "0.19"
wgpu = "0.6"
wgpu-subscriber = "0.1.0"
winit = { version = "0.23.0", features = ["serde"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }

#[[example]]
#name = "assets"
#path = "examples/assets.rs"

#[[example]]
#name = "ecs"
#path = "examples/ecs.rs"
