[package]
name = "dotrix"
version = "0.1.2"
authors = [
  "Elias Kartashov <elias@lowenware.com>",
  "Štěpán Wünsch <sw@lowenware.com>",
]
edition = "2018"
description = "3D Game Engine"
license = "MIT"

[dependencies]
base64 = "0.13.0"
bytemuck = { version = "1.4", features = ["derive"] }
cgmath = "0.17"
futures = { version = "0.3", default-features = false, features = ["std"] }
gltf = { version = "0.15", features = ["extras", "names"] }
log = "0.4"
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shaderc = "0.7"
strum = "0.19"
strum_macros = "0.19"
# wgpu = "0.6"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", branch = "master", features = ["trace"] }
wgpu-subscriber = "0.1.0"
winit = { version = "0.23.0", features = ["serde"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }

[[example]]
name = "demo"
path = "examples/demo/demo.rs"

[[example]]
name = "gltf"
path = "examples/gltf/gltf.rs"

[[example]]
name = "female"
path = "examples/animation/female.rs"

[[example]]
name = "fox"
path = "examples/animation/fox.rs"
