[package]
name = "dotrix"
version = "0.1.4"
authors = [
  "Elias Kartashov <elias@lowenware.com>",
  "Štěpán Wünsch <sw@lowenware.com>",
  "Nikita Zemtsov <z-nik@ya.ru>",
]
edition = "2018"
description = "3D Game Engine"
license = "MIT"

[features]
default = []

[dependencies]
base64 = "0.13.0"
bytemuck = { version = "1.4", features = ["derive"] }
cgmath = "0.17"
futures = { version = "0.3", default-features = false, features = ["std"] }
gltf = { version = "0.15", features = ["extras", "names"] }
log = "0.4"
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "2ef725065e68164cced1551c7a2540523eb0ca77", features = ["trace"] }
wgpu-subscriber = "0.1.0"
winit = { version = "0.23.0", features = ["serde"] }

# Optional dependenciew
shaderc = { version = "0.7", optional = true }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }

[[example]]
name = "demo"
path = "examples/demo/demo.rs"

[[example]]
name = "fox"
path = "examples/animation/fox.rs"

[[example]]
name = "skybox"
path = "examples/skybox/skybox.rs"
