[package]
name = "dotrix"
version = "0.1.0"
authors = ["Elias Kartashov <elias@lowenware.com>"]
edition = "2018"

# [features]
# default = [
#     "my_feature",
# ]

[dependencies]
dotrix_assets = { path = "crates/dotrix_assets", version = "0.1.0" }
dotrix_core = { path = "crates/dotrix_core", version = "0.1.0" }

[[example]]
name = "cube"
path = "examples/cube/cube.rs"
