[package]
name = "dotrix"
version = "0.2.0"
authors = [
  "Elias Kartashov <elias@lowenware.com>",
  "Štěpán Wünsch <sw@lowenware.com>",
  "Nikita Zemtsov <z-nik@ya.ru>",
]
edition = "2018"
description = "3D Game Engine"
license = "MIT"

[features]
default = ["ui"]
ui = ["dotrix_ui"]

[workspace]
members = [
  "dotrix_core",
  "dotrix_ui",
]

[dependencies.dotrix_core]
version = "0.2"
path = "./dotrix_core"

# Optional dependencies

[dependencies.dotrix_ui]
version = "0.2"
path = "./dotrix_ui"
optional = true

[dev-dependencies.cgmath]
version = "0.17"

[[example]]
name = "demo"
path = "examples/demo/demo.rs"

[[example]]
name = "fox"
path = "examples/animation/fox.rs"

[[example]]
name = "skybox"
path = "examples/skybox/skybox.rs"

[[example]]
name = "ui"
path = "examples/ui/ui.rs"